apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    server {
      listen 81;
      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
      }
    }
