apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0
  labels:
    type: pv0
spec:
  storageClassName: db-pv0
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/pv0
