apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  labels:
    type: pv1
spec:
  storageClassName: db-pv1
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/pv1
