apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  labels:
    type: pvc1
spec:
  storageClassName: db-pv1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
